---
- hosts: "{{ host_address }}"
  become: true
  pre_tasks:
  - name: Add free ipa local domain to known hosts
    lineinfile:
      path: /etc/hosts
      line: 172.30.1.123 ipa.perdix.co.local
  - name: create nfshome folder
    file:
      path: /nfshome
      state: directory 
  - name: install nfs client
    apt:
      name: ['nfs-common', 'sssd-tools', 'portmap'] 
      state: present
  - name: Do nfs mount on nfshome folder
    lineinfile:
      path: /etc/fstab
      line: 172.30.1.123:/nfshome /nfshome nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0
  vars:
    freeipaclient_server: "{  { ipaclient_realm }}"
    freeipaclient_domain: "{{ ipaclient_domain }}"
    freeipaclient_enroll_user: "{{ ipaclient_principal }}"
    freeipaclient_enroll_pass: "{{ ipaclient_password }}"
  roles:
     -  alvaroaleman.freeipa-client 
